<p><?= __('Hello, ') . $username; ?></p>
<p><?= __('Your account has been created successfully. All you have left to do is to activate it.') ?></p>
<p><?= __('Here is the confirmation link : ') . $this->Html->link($this->Html->url($link, true)); ?></p>
<p><?= __('Have a good day!') ?></p>
<p><?= __('___________________________________________________________________________________________________') ?></p>
<p><?= __('Bonjour, ') . $username; ?></p>
<p><?= __('Votre compte a été crée à merveille. Tout ce qui vous reste à faire est de l\'activé.') ?></p>
<p><?= __('Voila le lien de confirmation : ') . $this->Html->link($this->Html->url($link, true)); ?></p>
<p><?= __('Bonne journée!') ?></p>